name: 'Auto update flake'
description: 'Automatically update flake inputs if they pass CI'
author: 'Matthew Bauer'
inputs:
  cron:
    description: 'How often to run flake update in crontab schedule expression'
branding:
  color: 'blue'
  icon: 'sun'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
    - run: |
        git config --global user.email "auto-update-flake@github.com"
        git config --global user.name "Flake Auto Update"
        nix --extra-experimental-features 'nix-command flakes' flake update --commit-lock-file
        if nix --extra-experimental-features 'nix-command flakes' flake check; then
            git push
        fi
      shell: bash
