name: 'Auto update flake'
description: 'Automatically update flake inputs if they pass CI'
author: 'Matthew Bauer'
inputs:
  cron:
    description: 'How often to run flake update in crontab schedule expression'
branding:
  color: 'blue'
  icon: 'sun'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: |
        nix flake update --commit-lock-file
        if nix flake check; then
            git push origin master
        fi
      shell: bash
